### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by blowing-in-the-wind** [ehuacui/ehuacui-bbs#1]
主页功能链接404。访问地址http://localhost/bbs/ 主页能正常展示，但是点击各个入口链接会404（比如点击精华跳转：http://localhost/?tab=good ）... 
nginx是按bbs-doc的bbs.conf部署的（监听换成了80）。菜鸟求助

**Comment by koftt** [comment]
静态文件分开了  在D盘 nginx也配好了 ，  字体图标怎么不显示 显示不出来？明明都在里面  也引入了 ？

**Comment by blowing-in-the-wind** [comment]
解决了 = =

- 上面描述的异常跳转问题：将此工程配置为tomcat默认访问工程。
- 监听换回了4000，因为之前没注意到webconfig.properties这个配置文件...... 访问http://localhost:4000 ，一切正常。
